easy_admin:
    entities:
        # List the entity class name you want to manage
        Users:
            class: App\Entity\User
        Products:
            class: App\Entity\Products
            form:
                fields: ['name', 'img', 'brand', 'category', 'price', 'description']
        Categories:
            class: App\Entity\Categories
        Brands:
            class: App\Entity\Brands

